const projectName = "casino"

const gameItems = [
  {
    id: 1,
    name: "Treasure Chest",
    description: "A legendary chest sealed with ancient magic. Only the bravest adventurers will discover the riches within. Rumored to contain items of great power—or great danger.",
    image: "images/item-1.png",
    rarity: 500,
    effect: "loot",
  },
  {
    id: 2,
    name: "Mana Potion",
    description: "A shimmering vial of arcane liquid. Restores magical energy to wizards and spellcasters. One sip, and you'll feel the surge of mystical force flow through your veins.",
    image: "images/item-2.png",
    rarity: 100,
  },
  {
    id: 3,
    name: "Health Potion",
    description: "Distilled from enchanted herbs in the Forest of Eldara, this potion heals wounds and revitalizes the soul. A must-have for any hero diving into danger.",
    image: "images/item-3.png",
    rarity: 100,
  },
  {
    id: 4,
    name: "Gold Star",
    description: "A token of glory from the Celestial Realms. Grants temporary invincibility or bonus rewards when collected. Bright enough to light the darkest dungeon.",
    image: "images/item-4.png",
    rarity: 500,
  },
  {
    id: 5,
    name: "Cherries",
    description: "Twin bursts of juicy energy! Collect these to boost your luck and trigger mini bonuses. Sweet and explosive in the right combo.",
    image: "images/item-5.png",
    rarity: 200,
  },
  {
    id: 6,
    name: "Golden Crown",
    description: "Worn by champions and guarded by legends. This shimmering crown unlocks regal rewards and might just grant invincibility for a short reign.",
    image: "images/item-6.png",
    rarity: 400,
  },
  {
    id: 7,
    name: "Heart",
    description: "A radiant symbol of vitality and emotion. Restores your health, fuels your courage, and might awaken secret paths when your heart is full.",
    image: "images/item-7.png",
    rarity: 250,
  },
  {
    id: 8,
    name: "Strawberry",
    description: "Nature’s candy with a twist—packed with power! This fruity gem adds a speed boost and leaves a trail of sweetness in your wake.",
    image: "images/item-8.png",
    rarity: 80,
  },
  {
    id: 9,
    name: "Card - Ace of Spades",
    description: "Symbol of power, fate, and hidden strength. Often associated with skilled tacticians and risk-takers. Beware: the Ace of Spades plays for keeps.",
    image: "images/item-9.png",
    rarity: 100,
  },
  {
    id: 10,
    name: "Card - Ace of Hearts",
    description: "Emblem of passion, courage, and life. Wielded by heroes of the heart, this card inspires loyalty and heals emotional wounds as much as physical ones.",
    image: "images/item-10.png",
    rarity: 100,
  },
  {
    id: 11,
    name: "Card - Ace of Clubs",
    description: "A mark of resilience and brute force. Often favored by warriors and guardians, the Ace of Clubs signifies strength in unity and overwhelming power.",
    image: "images/item-11.png",
    rarity: 100,
  },
  {
    id: 12,
    name: "Card - Ace of Diamonds",
    description: "Gleaming with ambition and wealth, this card represents precision and clarity. Master tacticians and merchants alike draw this card to tip fate in their favor.",
    image: "images/item-12.png",
    rarity: 100,
  },
  {
    id: 13,
    name: "Orange Slice",
    description: "One bite, and you're zipping through the level with electric zest. Restores stamina and charges your energy bar with a citrusy zing.",
    image: "images/item-13.png",
    rarity: 50,
  },
  {
    id: 14,
    name: "Golden Key",
    description: "Not just for doors—this mystical key opens treasure chests, hidden levels, and occasionally… time portals.",
    image: "images/item-14.png",
    rarity: 300,
  },
  {
    id: 15,
    name: "Potion Vial",
    description: "A swirling mix of magic and mischief. Drink at your own risk—effects range from invincibility to temporary flight. Or… hiccups.",
    image: "images/item-15.png",
    rarity: 100,
  },
  {
    id: 16,
    name: "Chips",
    description: "Tokens of fate used in games of luck and skill. Trade them in for powerful rewards—or risk them for a jackpot!",
    image: "images/item-16.png",
    rarity: 50,
  },
  {
    id: 17,
    name: "Coin Pouch",
    description: "A weighty sack of gold, jingling with promise. The sound of success to merchants—and a target for thieves.",
    image: "images/item-17.png",
    rarity: 250,
  },
  {
    id: 18,
    name: "Coin",
    description: "Shiny and satisfying. Currency of the realm, accepted by merchants, mercenaries, and dragons alike.",
    image: "images/item-18.png",
    rarity: 50,
  },
  {
    id: 19,
    name: "Gold Bar",
    description: "A heavy bar of pure gold. Perfect for trade, bribery, or impressing dragons. Increases your wealth and may unlock secret merchant deals.",
    image: "images/item-19.png",
    rarity: 250,
  },
  {
    id: 20,
    name: "Green Apple",
    description: "Crisp, dewy, and unnaturally perfect—this apple holds a secret just beneath its shiny skin. Bite at your own curiosity.",
    image: "images/item-20.png",
    rarity: 50,
  },
  {
    id: 21,
    name: "Pink Gem",
    description: "This radiant crystal hums softly with an unspoken energy, shifting hues when held close to the heart.",
    image: "images/item-21.png",
    rarity: 500,
  },
  {
    id: 22,
    name: "Diamond",
    description: "Sharp edges, cool to the touch, and glimmering with a frozen light. It seems to pulse in rhythm with silent tides.",
    image: "images/item-22.png",
    rarity: 1000,
  },
  {
    id: 23,
    name: "Clock",
    description: "Tick-tock through time itself. Grants you extra turns, slows enemies, or even rewinds fate... for a price.",
    image: "images/item-23.png",
    rarity: 50,
  },
  {
    id: 24,
    name: "Gold Lightning",
    description: "Raw, untamed energy. Boosts your speed, powers your special attacks, or shocks enemies into submission.",
    image: "images/item-24.png",
    rarity: 125,
  },
  {
    id: 25,
    name: "Blue Lightning",
    description: "A surge of icy electricity. Enhances your defense, restores energy, or freezes time for a blink.",
    image: "images/item-25.png",
    rarity: 125,
  },
  {
    id: 26,
    name: "Dice",
    description: "Roll these enchanted dice to test fate. May bring fortune… or chaos.",
    image: "images/item-26.png",
    rarity: 100,
  },
  {
    id: 27,
    name: "Raspberry",
    description: "Each bulbous drupelet bursts with sweetness and mystery. Too ripe to be ordinary, too vivid to ignore.",
    image: "images/item-27.png",
    rarity: 50,
  },
  {
    id: 28,
    name: "Bomb",
    description: "Compact, round, and deceptively playful, this ticking globe exudes a mischievous glow. Its silence is louder than a countdown.",
    image: "images/item-28.png",
    rarity: 50,
  },
  {
    id: 29,
    name: "Amethyst",
    description: "A shard of twilight, humming faintly with echoes of forgotten stars.",
    image: "images/item-29.png",
    rarity: 500,
  },
  {
    id: 30,
    name: "Emerald",
    description: "A sliver of the forest's heart, still damp with morning dew and secrets.",
    image: "images/item-30.png",
    rarity: 500,
  },
  {
    id: 31,
    name: "Lock",
    description: "Cold to the touch, yet somehow listening—waiting for a name never spoken aloud.",
    image: "images/item-31.png",
    rarity: 100,
  },
  {
    id: 32,
    name: "Gift Box",
    description: "Wrapped in color and tied with luck, this gift could hold anything from coins to crazy bonuses. Dare to unwrap?",
    image: "images/item-32.png",
    rarity: 500,
    effect: "loot",
  },
  {
    id: 35,
    name: "Cherries Pack",
    description: "Cherries card pack is your ticket to a world of bluff, luck, and bold strategy. Inside, you'll find rare wild cards, tricked-out high rollers, and risk-it-all game changers. Are you just playing the game, or are you ready to beat the house?",
    image: "images/item-35.png",
    rarity: 500,
    effect: "loot",
    items: [9, 10, 11, 12],
  },
]